language: node_js
node_js:
  - 6
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
sudo: false
cache:
  directories:
    - node_modules
after_success:
  test "$TRAVIS_TAG" &&
  test $TRAVIS_TEST_RESULT -eq 0 &&
  echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc &&
  npm publish
